name: Publish Python Package

on:
  push:
    tags:
      - 'v*.*.*'
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel build twine

      - name: Build distribution
        run: |
          python -m build --sdist --wheel

      - name: Publish to TestPyPI
        if: github.event_name == 'push'
        env:
          TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          python -m twine upload \
            --repository testpypi \
            --non-interactive \
            -u __token__ \
            -p "$TEST_PYPI_API_TOKEN" \
            dist/*

      - name: Publish to PyPI
        if: github.event_name == 'release'
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload \
            --non-interactive \
            -u __token__ \
            -p "$PYPI_API_TOKEN" \
            dist/*
